Repository AY2122S1-CS2103T-T11-3/tp, pull requests merged in 2021-11, with the labels that each got.

#144 Add implementation dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddAppointmentActivityDiagram.puml
  docs/diagrams/AddAppointmentSequenceDiagram.puml
  docs/diagrams/DeleteAppointmentActivityDiagram.puml
  docs/diagrams/DeleteAppointmentSequenceDiagram.puml
  docs/images/AddAppointmentActivityDiagram.png
  docs/images/AddAppointmentSequenceDiagram.png
  docs/images/DeleteAppointmentActivityDiagram.png
  docs/images/DeleteAppointmentSequenceDiagram.png
  docs/team/chuangzhequan.md
  docs/team/jiayi1129.md
  src/main/java/seedu/plannermd/logic/commands/apptcommand/AddAppointmentCommand.java
Labels: documentation

#206 Fix PED bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/plannermd/commons/core/Messages.java
  src/main/java/seedu/plannermd/logic/commands/ClearCommand.java
  src/main/java/seedu/plannermd/logic/parser/addcommandparser/AddDoctorCommandParser.java
  src/main/java/seedu/plannermd/logic/parser/editcommandparser/EditDoctorCommandParser.java
  src/test/java/seedu/plannermd/logic/parser/addcommandparser/AddDoctorCommandParserTest.java
  src/test/java/seedu/plannermd/logic/parser/editcommandparser/EditDoctorCommandParserTest.java
Labels: type.Task

#231 Allow names, emails and addresses that are too long to wrap
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/DoctorListCard.fxml
  src/main/resources/view/PatientListCard.fxml
Labels: bug, severity.VeryLow

#222 Display error message when user use the filter upcoming appointment command with date parameters
  src/main/java/seedu/plannermd/commons/core/Messages.java
  src/main/java/seedu/plannermd/logic/commands/apptcommand/ListAppointmentCommand.java
  src/main/java/seedu/plannermd/logic/parser/apptcommandparser/FilterAppointmentCommandParser.java
  src/main/java/seedu/plannermd/logic/parser/apptcommandparser/FilterUpcomingAppointmentCommandParser.java
  src/main/java/seedu/plannermd/model/appointment/AppointmentDate.java
  src/test/java/seedu/plannermd/logic/commands/apptcommand/ListAppointmentCommandTest.java
  src/test/java/seedu/plannermd/logic/parser/apptcommandparser/FilterUpcomingAppointmentCommandParserTest.java
Labels: type.Task, priority.Medium

#223 Add manual testing
  docs/DeveloperGuide.md
  src/main/java/seedu/plannermd/logic/commands/addcommand/AddDoctorCommand.java
  src/main/java/seedu/plannermd/logic/commands/addcommand/AddPatientCommand.java
Labels: documentation

#235 Update tag command to detect existing tags
  src/main/java/seedu/plannermd/logic/commands/apptcommand/AppointmentCommand.java
  src/main/java/seedu/plannermd/logic/commands/apptcommand/FilterAppointmentCommand.java
  src/main/java/seedu/plannermd/logic/commands/tagcommand/AddDoctorTagCommand.java
  src/main/java/seedu/plannermd/logic/commands/tagcommand/AddPatientTagCommand.java
  src/main/java/seedu/plannermd/logic/commands/tagcommand/AddTagCommand.java
  src/main/java/seedu/plannermd/logic/commands/tagcommand/DeleteDoctorTagCommand.java
  src/main/java/seedu/plannermd/logic/commands/tagcommand/TagCommand.java
  src/test/java/seedu/plannermd/logic/commands/CommandTestUtil.java
  src/test/java/seedu/plannermd/logic/commands/tagcommand/AddDoctorTagCommandTest.java
  src/test/java/seedu/plannermd/logic/commands/tagcommand/AddPatientTagCommandTest.java
Labels: bug

#234 [Li Xue] Update project portfolio page
  docs/team/pualixue.md
Labels: documentation

#233 Update DG manual testing
  docs/DeveloperGuide.md
Labels: documentation

#228 Update DG with use cases and manual testing instructions for listing and filtering appointments
  docs/DeveloperGuide.md
  docs/diagrams/AppointmentFilterSequenceDiagram.puml
  docs/images/AppointmentFilterSequenceDiagram.png
Labels: documentation, priority.Medium

#237 Add Find Patient/Doctor and Saving data manual testing
  docs/DeveloperGuide.md
Labels: documentation

#229 [Hao Ze] Update personal contributions
  docs/team/haozeee.md
Labels: documentation

#249 Fix FilterAppointment sequence diagram typo
  docs/diagrams/AppointmentFilterSequenceDiagram.puml
Labels: bug, documentation, severity.VeryLow

#227 [Zhe Quan] Add PPP
  docs/team/ChuangZheQuan.md
  docs/team/chuangzhequan.md
Labels: documentation

#242 Edit person no longer returns to the unfiltered list after editing a Person
  src/main/java/seedu/plannermd/logic/commands/editcommand/EditDoctorCommand.java
  src/main/java/seedu/plannermd/logic/commands/editcommand/EditPatientCommand.java
  src/test/java/seedu/plannermd/logic/commands/editcommand/EditDoctorCommandTest.java
  src/test/java/seedu/plannermd/logic/commands/editcommand/EditPatientCommandTest.java
Labels: bug, severity.Low

#246 Mention adding test cases in PPP
  docs/team/pualixue.md
Labels: documentation

#251 Update user stories
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#252 Sequence diagram: break method calls into two lines
  docs/diagrams/EditAppointmentSequenceDiagram.puml
  docs/images/EditAppointmentSequenceDiagram.png
Labels: documentation

#263 Update list appointment manual testing
  docs/DeveloperGuide.md
Labels: documentation

#272 Update manual testing error messages
  docs/DeveloperGuide.md
Labels: documentation

#278 Add page breaks to UG/DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jiayi1129.md
Labels: documentation

#289 Update PPP
  docs/team/pualixue.md
Labels: documentation
