Repository AY2122S1-CS2103T-T11-3/tp, pull requests merged in 2021-10, with the labels that each got.

#53 Add Doctor Skeleton
  src/main/java/seedu/plannermd/model/doctor/Doctor.java
Labels: type.Task, priority.High

#41 Add Remark feature
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/plannermd/logic/commands/RemarkCommand.java
  src/main/java/seedu/plannermd/logic/commands/editcommand/EditPatientCommand.java
  src/main/java/seedu/plannermd/logic/parser/AddCommandParser.java
  src/main/java/seedu/plannermd/logic/parser/CliSyntax.java
  src/main/java/seedu/plannermd/logic/parser/PlannerMdParser.java
  src/main/java/seedu/plannermd/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/plannermd/model/doctor/Doctor.java
  src/main/java/seedu/plannermd/model/patient/Patient.java
  src/main/java/seedu/plannermd/model/person/Person.java
  src/main/java/seedu/plannermd/model/person/Remark.java
  src/main/java/seedu/plannermd/model/util/SampleDataUtil.java
  src/main/java/seedu/plannermd/storage/JsonAdaptedPatient.java
  src/main/java/seedu/plannermd/storage/JsonAdaptedPerson.java
  src/test/data/JsonPlannerMdStorageTest/invalidAndValidPatientPlannerMd.json
  src/test/data/JsonSerializablePlannerMdTest/duplicatePatientPlannerMd.json
  src/test/data/JsonSerializablePlannerMdTest/typicalPatientsPlannerMd.json
  src/test/java/seedu/plannermd/logic/commands/CommandTestUtil.java
  src/test/java/seedu/plannermd/logic/commands/EditPatientCommandTest.java
  src/test/java/seedu/plannermd/logic/commands/FindPatientCommandTest.java
  src/test/java/seedu/plannermd/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/plannermd/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/plannermd/model/person/RemarkTest.java
  src/test/java/seedu/plannermd/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/plannermd/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/plannermd/testutil/PersonBuilder.java
  src/test/java/seedu/plannermd/testutil/TypicalPersons.java
  src/test/java/seedu/plannermd/testutil/patient/PatientBuilder.java
  src/test/java/seedu/plannermd/testutil/patient/TypicalPatients.java
Labels: enhancement

#40 Allow adding and deleting individual tags
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/pualixue.md
  src/main/java/seedu/plannermd/logic/commands/tagcommand/AddPatientTagCommand.java
  src/main/java/seedu/plannermd/logic/commands/tagcommand/AddTagCommand.java
  src/main/java/seedu/plannermd/logic/commands/tagcommand/DeletePatientTagCommand.java
  src/main/java/seedu/plannermd/logic/commands/tagcommand/DeleteTagCommand.java
  src/main/java/seedu/plannermd/logic/parser/CliSyntax.java
  src/main/java/seedu/plannermd/logic/parser/Flag.java
  src/main/java/seedu/plannermd/logic/parser/PlannerMdParser.java
  src/main/java/seedu/plannermd/logic/parser/TagCommandParser.java
  src/main/java/seedu/plannermd/model/patient/Patient.java
  src/main/java/seedu/plannermd/model/person/Person.java
  src/test/java/seedu/plannermd/logic/commands/AddPatientTagCommandTest.java
  src/test/java/seedu/plannermd/logic/commands/DeletePatientTagCommandTest.java
  src/test/java/seedu/plannermd/logic/parser/FlagTest.java
  src/test/java/seedu/plannermd/logic/parser/TagCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#55 Update UI with doctors
  src/main/java/seedu/plannermd/MainApp.java
  src/main/java/seedu/plannermd/model/Model.java
  src/main/java/seedu/plannermd/model/ModelManager.java
  src/main/java/seedu/plannermd/ui/DoctorCard.java
  src/main/java/seedu/plannermd/ui/DoctorListPanel.java
  src/main/java/seedu/plannermd/ui/MainWindow.java
  src/main/java/seedu/plannermd/ui/PatientCard.java
  src/main/java/seedu/plannermd/ui/PatientListPanel.java
  src/main/java/seedu/plannermd/ui/PersonCard.java
  src/main/java/seedu/plannermd/ui/PersonTab.java
  src/main/java/seedu/plannermd/ui/PersonTabSwitcher.java
  src/main/java/seedu/plannermd/ui/Ui.java
  src/main/java/seedu/plannermd/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DoctorListCard.fxml
  src/main/resources/view/DoctorListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/PersonTab.fxml
  src/test/java/seedu/plannermd/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/plannermd/model/ModelManagerTest.java
Labels: priority.Medium

#38 Update Person class duplicate checks
  src/main/java/seedu/plannermd/model/person/Person.java
  src/test/java/seedu/plannermd/model/person/PersonTest.java
Labels: type.Task, priority.Medium

#67 Change Person equality checks to be case insensetive
  src/main/java/seedu/plannermd/model/person/Address.java
  src/main/java/seedu/plannermd/model/person/Email.java
  src/main/java/seedu/plannermd/model/person/Name.java
  src/test/java/seedu/plannermd/model/person/PersonTest.java
Labels: type.Task

#68 Fix edit birth date bug
  src/main/java/seedu/plannermd/logic/commands/editcommand/EditPatientCommand.java
  src/test/java/seedu/plannermd/logic/commands/EditPatientDescriptorTest.java
Labels: bug

#71 Resolve Edit Risk bug
  src/main/java/seedu/plannermd/logic/parser/EditCommandParser.java
  src/main/java/seedu/plannermd/logic/parser/ParserUtil.java
  src/main/java/seedu/plannermd/model/patient/Risk.java
  src/test/java/seedu/plannermd/logic/commands/CommandTestUtil.java
  src/test/java/seedu/plannermd/logic/commands/EditPatientCommandTest.java
  src/test/java/seedu/plannermd/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/plannermd/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/plannermd/logic/parser/PlannerMdParserTest.java
  src/test/java/seedu/plannermd/testutil/PersonUtil.java
  src/test/java/seedu/plannermd/testutil/patient/EditPatientDescriptorBuilder.java
  src/test/java/seedu/plannermd/testutil/patient/TypicalPatients.java
Labels: type.Bug, priority.High, severity.Medium

#62 Delete doctors
  src/main/java/seedu/plannermd/commons/core/Messages.java
  src/main/java/seedu/plannermd/logic/commands/deletecommand/DeleteDoctorCommand.java
  src/main/java/seedu/plannermd/logic/parser/DeleteDoctorCommandParser.java
  src/main/java/seedu/plannermd/logic/parser/DeletePatientCommandParser.java
  src/main/java/seedu/plannermd/logic/parser/PlannerMdParser.java
  src/main/java/seedu/plannermd/model/PlannerMd.java
  src/test/java/seedu/plannermd/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/plannermd/logic/commands/CommandTestUtil.java
  src/test/java/seedu/plannermd/logic/commands/DeleteDoctorCommandTest.java
  src/test/java/seedu/plannermd/logic/commands/DeletePatientCommandTest.java
  src/test/java/seedu/plannermd/logic/parser/DeleteDoctorCommandParserTest.java
  src/test/java/seedu/plannermd/logic/parser/DeletePatientCommandParserTest.java
  src/test/java/seedu/plannermd/logic/parser/PlannerMdParserTest.java
  src/test/java/seedu/plannermd/model/ModelManagerTest.java
Labels: type.Story, priority.High

#85 Set tabs to be unclicakble with mouse
  src/main/java/seedu/plannermd/ui/PersonTab.java
Labels: type.Task, priority.Medium

#88 Fix error message for add command
  src/main/java/seedu/plannermd/logic/commands/addcommand/AddDoctorCommand.java
  src/main/java/seedu/plannermd/logic/commands/addcommand/AddPatientCommand.java
Labels: bug, priority.Low, severity.VeryLow

#86 Fix responses for birth date and edit doctor
  src/main/java/seedu/plannermd/logic/commands/editcommand/EditDoctorCommand.java
  src/main/java/seedu/plannermd/model/person/BirthDate.java
Labels: bug

#95 Create Appointment class
  src/main/java/seedu/plannermd/model/appointment/Appointment.java
  src/main/java/seedu/plannermd/model/appointment/AppointmentDate.java
  src/main/java/seedu/plannermd/model/appointment/Duration.java
  src/main/java/seedu/plannermd/model/appointment/Session.java
  src/test/java/seedu/plannermd/model/appointment/AppointmentDateTest.java
  src/test/java/seedu/plannermd/model/appointment/DurationTest.java
  src/test/java/seedu/plannermd/model/appointment/SessionTest.java
  src/test/java/seedu/plannermd/model/person/BirthDateTest.java
Labels: enhancement, priority.High

#179 Fix ped bugs
  docs/UserGuide.md
  src/main/java/seedu/plannermd/logic/commands/apptcommand/AddAppointmentCommand.java
  src/main/java/seedu/plannermd/model/person/BirthDate.java
Labels: bug

#191 Add test cases for Appointment class
  src/test/java/seedu/plannermd/model/appointment/AppointmentTest.java
Labels: priority.Medium

#196 Add UniqueAppointmentList tests
  src/test/java/seedu/plannermd/model/appointment/UniqueAppointmentListTest.java
Labels: type.Task, priority.Low

#197 Update record managing feature guide
  docs/UserGuide.md
  docs/images/doctorTab.png
  docs/images/patientTab.png
  docs/images/toggleTabs.png
Labels: documentation

#192 Update dg with filter appointment details and UI component
  docs/DeveloperGuide.md
  docs/diagrams/AppointmentFilterSequenceDiagram.puml
  docs/diagrams/ConfigureAppointmentFilters.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AppointmentFilterSequenceDiagram.png
  docs/images/ConfigureAppointmentFilters.png
  docs/images/UiClassDiagram.png
Labels: documentation

#195 Update Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditAppointmentSequenceDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/EditAppointmentSequenceDiagram.png
  docs/images/ParserClasses.png
Labels: documentation, priority.Medium

#188 Disallow appointments to span two days
  src/main/java/seedu/plannermd/logic/commands/apptcommand/EditAppointmentCommand.java
  src/main/java/seedu/plannermd/logic/parser/apptcommandparser/AddAppointmentCommandParser.java
  src/main/java/seedu/plannermd/model/appointment/Session.java
  src/test/java/seedu/plannermd/logic/commands/apptcommand/EditAppointmentCommandTest.java
  src/test/java/seedu/plannermd/logic/parser/apptcommandparser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/plannermd/model/appointment/SessionTest.java
Labels: bug

#190 Fix adding appointments not shown in appointment list and overflowing tags
  docs/UserGuide.md
  src/main/java/seedu/plannermd/logic/commands/apptcommand/AddAppointmentCommand.java
  src/main/java/seedu/plannermd/logic/commands/apptcommand/AppointmentFilters.java
  src/main/resources/view/AppointmentListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/plannermd/logic/commands/apptcommand/AddAppointmentCommandIntegrationTest.java
  src/test/java/seedu/plannermd/logic/commands/apptcommand/AddAppointmentCommandTest.java
Labels: bug, severity.Medium

#204 Fix time error message
  src/main/java/seedu/plannermd/logic/commands/apptcommand/AddAppointmentCommand.java
  src/main/java/seedu/plannermd/logic/commands/apptcommand/EditAppointmentCommand.java
  src/main/java/seedu/plannermd/model/appointment/Session.java
Labels: priority.Low

#198 Update Appointment Storage Implementation in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AppointmentStorageSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/AppointmentStorageSequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Task
